config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    namespace :reports do
      resources :steps
    end
    namespace :problems do
      resources :steps
    end
    resources :reports, only: [:index, :show, :edit, :update]
    resources :taxonomies, :categories, :problems, :pages
    resources :organizations
    get 'analytics' => 'analytics#index'
    root to: "dashboard#index"
  end

  resources :reports, only: :create
  get 'publicites' => 'problems#index', as: :problems
  get 'publicites/:id' => 'problems#show', as: :problem
  get 'analyses' => 'problems#analyzed', as: :analyzed_problems
  get 'organisations/:slug' => 'organizations#show', as: :organization
  get ':taxonomy_slug' => 'categories#index', as: :taxonomy, constraints: lambda { |request|
    request.path.remove("/").in? Taxonomy.pluck(:slug)
  }
  get ':taxonomy_slug/:category_slug' => 'categories#show', as: :category

  get 'up' => "rails/health#show", as: :rails_health_check
  
  root to: 'pages#index'
  
  match "*slug" => "pages#show", via: :get, constraints: lambda { |request|
    request.path.exclude? 'rails/active_storage'
  }
end

app/views/admin/pages/_form.html.erb
<%= simple_form_for [:admin, @page] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <div class="row">
      <div class="col-lg-5">
        <%= f.input :title %>
      </div>
      <div class="col-lg-4">
        <%= f.input :slug, 
                    input_html: f.object.persisted? ? {} : {
                      class: 'js-slug-input',
                      data: { source: '#page_title' }
                    } %>
    </div>
    <div class="col-lg-3">
      <%= f.input :position %>
    </div>
    </div>
    <%= f.input :markdown,
                input_html: { rows: 20 },
                hint: t('admin.markdown_hint') %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, t('admin.save'), class: button_classes %>
  </div>
<% end %>

app/views/admin/pages/_list.html.erb
<table class="table">
  <thead>
    <tr>
      <th><%= Page.human_attribute_name(:title) %></th>
      <th><%= Page.human_attribute_name(:slug) %></th>
      <th><%= Page.human_attribute_name(:position) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% pages.each do |page| %>
      <tr>
        <td><%= link_to page, [:admin, page] %></td>
        <td><%= page.slug %></td>
        <td><%= page.position %></td>
        <td><%= link_to 'Supprimer', 
                        [:admin, page],
                        method: :delete,
                        data: { confirm: 'Vraiment ?' },
                        class: 'text-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/pages/edit.html.erb
<% content_for :title, @page %>
<%= render "form", page: @page %>

app/views/admin/pages/index.html.erb
<% content_for :title, Page.model_name.human(count: 2) %>

<%= render 'admin/pages/list', pages: @pages %>

<% content_for :buttons do %>
  <%= link_to t('admin.create'), new_admin_page_path, class: button_classes %>
<% end %>

app/views/admin/pages/new.html.erb
<% content_for :title, t('admin.create') %>
<%= render "form", page: @page %>

app/views/admin/pages/show.html.erb
<% content_for :title, @page %>

<div class="row">
  <div class="col-lg-8">
    <%= @page.html %>
  </div>
</div>

<% content_for :buttons do %>
  <%= link_to t('admin.edit'), edit_admin_page_path(@page), class: button_classes %>
<% end %>