config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    namespace :reports do
      resources :steps
    end
    namespace :problems do
      resources :steps
    end
    resources :reports, only: [:index, :show, :edit, :update]
    resources :taxonomies, :categories, :problems, :pages
    resources :organizations
    get 'analytics' => 'analytics#index'
    root to: "dashboard#index"
  end

  resources :reports, only: :create
  get 'publicites' => 'problems#index', as: :problems
  get 'publicites/:id' => 'problems#show', as: :problem
  get 'analyses' => 'problems#analyzed', as: :analyzed_problems
  get 'organisations/:slug' => 'organizations#show', as: :organization
  get ':taxonomy_slug' => 'categories#index', as: :taxonomy, constraints: lambda { |request|
    request.path.remove("/").in? Taxonomy.pluck(:slug)
  }
  get ':taxonomy_slug/:category_slug' => 'categories#show', as: :category

  get 'up' => "rails/health#show", as: :rails_health_check
  
  root to: 'pages#index'
  
  match "*slug" => "pages#show", via: :get, constraints: lambda { |request|
    request.path.exclude? 'rails/active_storage'
  }
end

app/models/taxonomy.rb
# == Schema Information
#
# Table name: taxonomies
#
#  id          :uuid             not null, primary key
#  description :text
#  for_reports :boolean          default(FALSE)
#  position    :integer          default(0)
#  slug        :string
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Taxonomy < ApplicationRecord
  include WithSlug

  has_many :categories

  validates_presence_of :title

  scope :for_reports, -> { where(for_reports: true) }
  scope :ordered, -> { order(:position) }
  scope :main, -> { ordered.first }

  def to_s
    "#{title}"
  end
end

app/controllers/admin/taxonomies_controller.rb
class Admin::TaxonomiesController < Admin::ApplicationController
  before_action :set_taxonomy, only: %i[ show edit update destroy ]

  def index
    @taxonomies = Taxonomy.all
  end

  def show
    @categories = @taxonomy.categories.ordered
  end

  def new
    @taxonomy = Taxonomy.new
  end

  def edit
  end

  def create
    @taxonomy = Taxonomy.new(taxonomy_params)
    if @taxonomy.save
      redirect_to [:admin, @taxonomy], notice: t('admin.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @taxonomy.update(taxonomy_params)
      redirect_to [:admin, @taxonomy], notice: t('admin.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @taxonomy.destroy!
    redirect_to admin_taxonomies_path, status: :see_other, notice: t('admin.deleted')
  end

  private

  def set_taxonomy
    @taxonomy = Taxonomy.find(params.expect(:id))
  end

  def taxonomy_params
    params.expect(taxonomy: [ :title, :slug, :description, :position, :for_reports ])
  end
end

app/views/admin/taxonomies/_form.html.erb
<%= simple_form_for [:admin, taxonomy] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <%= f.input :title %>
  <%= f.input :slug, 
              input_html: f.object.persisted? ? {} : {
                class: 'js-slug-input',
                data: { source: '#taxonomy_title' }
              } %>
  <%= f.input :for_reports %>
  <%= f.input :description, input_html: { rows: 5 } %>
  <%= f.input :position %>

  <%= f.button :submit, t('admin.save'), class: button_classes %>
<% end %>

app/views/admin/taxonomies/_list.html.erb
<table class="table">
  <thead>
    <tr>
      <th><%= Taxonomy.human_attribute_name(:title) %></th>
      <th><%= Taxonomy.human_attribute_name(:position) %></th>
      <th><%= Taxonomy.human_attribute_name(:categories) %></th>
    </tr>
  </thead>
  <tbody>
    <% taxonomies.ordered.each do |taxonomy| %>
      <tr>
        <td><%= link_to taxonomy, [:admin, taxonomy] %></td>
        <td><%= taxonomy.position %></td>
        <td><%= taxonomy.categories.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/taxonomies/edit.html.erb
<% content_for :title, @taxonomy %>

<%= render "form", taxonomy: @taxonomy %>

app/views/admin/taxonomies/index.html.erb
<% content_for :title, Taxonomy.model_name.human(count: 2) %>

<%= render 'admin/taxonomies/list', taxonomies: @taxonomies %>

<% content_for :buttons do %>
  <%= link_to t('admin.create'), new_admin_taxonomy_path, class: button_classes %>
<% end %>

app/views/admin/taxonomies/new.html.erb
<% content_for :title, t('admin.create') %>
<%= render "form", taxonomy: @taxonomy %>

app/views/admin/taxonomies/show.html.erb
<% content_for :title, @taxonomy %>

<p><%= @taxonomy.description.truncate_words(20) %></p>

<%= render 'admin/categories/list', categories: @categories %>

<% content_for :buttons do %>
  <%= link_to 'Ajouter', new_admin_category_path(taxonomy_id: @taxonomy.id), class: button_classes %>
<% end %>