config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    namespace :reports do
      resources :steps
    end
    namespace :problems do
      resources :steps
    end
    resources :reports, only: [:index, :show, :edit, :update]
    resources :taxonomies, :categories, :problems, :pages
    resources :organizations
    get 'analytics' => 'analytics#index'
    root to: "dashboard#index"
  end

  resources :reports, only: :create
  get 'publicites' => 'problems#index', as: :problems
  get 'publicites/:id' => 'problems#show', as: :problem
  get 'analyses' => 'problems#analyzed', as: :analyzed_problems
  get 'organisations/:slug' => 'organizations#show', as: :organization
  get ':taxonomy_slug' => 'categories#index', as: :taxonomy, constraints: lambda { |request|
    request.path.remove("/").in? Taxonomy.pluck(:slug)
  }
  get ':taxonomy_slug/:category_slug' => 'categories#show', as: :category

  get 'up' => "rails/health#show", as: :rails_health_check
  
  root to: 'pages#index'
  
  match "*slug" => "pages#show", via: :get, constraints: lambda { |request|
    request.path.exclude? 'rails/active_storage'
  }
end

app/models/problem.rb
# == Schema Information
#
# Table name: problems
#
#  id          :uuid             not null, primary key
#  description :text
#  title       :string
#  year        :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  step_id     :uuid
#
# Indexes
#
#  index_problems_on_step_id  (step_id)
#
# Foreign Keys
#
#  fk_rails_...  (step_id => problem_steps.id)
#
class Problem < ApplicationRecord
  include WithSteps

  has_many :reports
  has_and_belongs_to_many :categories
  has_and_belongs_to_many :organizations

  has_one_attached :image

  validates_presence_of :year

  scope :ordered, -> { order(created_at: :desc) }
  scope :normal_and_important, -> { joins(:step).where('problem_steps.importance >= 0') }
  scope :important, -> { joins(:step).where('problem_steps.importance > 0') }
  scope :for_home, -> { important.ordered.limit(4) }

  def identifier
    id.split('-').first.upcase
  end

  def main_categories
    categories.where(id: Taxonomy.main.categories)
  end

  def important?
    step.importance == 'high'
  end

  def reported_by
    @reported_by ||= reports.pluck(:author_pseudonym)
                            .uniq
                            .compact_blank
                            .sort
  end

  def description_to_html
    MarkdownRenderer.new(description).html
  end

  def to_s
    "#{title}"
  end
end

app/models/problem/facets.rb
class Problem::Facets < FacetedSearch::Facets
  def initialize(params)
    super
    @model = Problem.normal_and_important
    filter_with_text :title, {
      title: 'Filtres'
    }
    filter_with_list :step, {
      title: Problem.human_attribute_name(:step),
      source: Problem::Step.all
    }
    ::Taxonomy.ordered.each do |taxonomy|
      add_facet ::FacetedSearch::Facets::Taxonomy,
                taxonomy.slug, 
                { taxonomy: taxonomy }
    end
  end
end

app/models/problem/step.rb
# == Schema Information
#
# Table name: problem_steps
#
#  id          :uuid             not null, primary key
#  color       :string           default("#666666")
#  description :text
#  importance  :integer          default("medium")
#  position    :integer          default(0)
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Problem::Step < ApplicationRecord
  has_many :problems

  scope :ordered, -> { order(:position) }
  scope :analyzed, -> { where('position > 9') }

  enum :importance, {
    low: -1,
    medium: 0,
    high: 1
  }

  def to_s
    "#{title}"
  end
end

app/controllers/admin/problems/steps_controller.rb
class Admin::Problems::StepsController < Admin::ApplicationController
  before_action :set_step, only: %i[ show edit update destroy ]

  def index
    @steps = Problem::Step.ordered
  end

  def show
  end

  def new
    @step = Problem::Step.new
  end

  def edit
  end

  def create
    @step = Problem::Step.new(step_params)
    if @step.save
      redirect_to admin_problems_step_path(@step), notice: t('admin.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @step.update(step_params)
      redirect_to admin_problems_step_path(@step), notice: t('admin.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @step.destroy!
    redirect_to admin_problems_steps_path, status: :see_other, notice: t('admin.deleted')
  end

  private

    def set_step
      @step = Problem::Step.find(params.expect(:id))
    end

    def step_params
      params.expect(problem_step: [ :title, :description, :position, :color, :importance ])
    end
end

app/controllers/admin/problems_controller.rb
class Admin::ProblemsController < Admin::ApplicationController
  before_action :set_problem, only: %i[ show edit update destroy ]

  def index
    @problems = Problem.all
    if params[:step]
      @step = Problem::Step.find(params[:step])
      @problems = @problems.where(step: @step)
    end
  end

  def show
  end

  def new
    @problem = Problem.new
  end

  def edit
  end

  def create
    @problem = Problem.new(problem_params)
    if @problem.save
      redirect_to [:admin, @problem], notice: t('admin.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @problem.update(problem_params)
      redirect_to [:admin, @problem], notice: t('admin.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @problem.destroy!
    redirect_to admin_problems_path, status: :see_other, notice: t('admin.deleted')
  end

  private

    def set_problem
      @problem = Problem.find(params.expect(:id))
    end

    def problem_params
      params.expect(problem: [ :title, :year, :description, :image, :step_id, category_ids: [], organization_ids: [] ])
    end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  def index
    @facets = Problem::Facets.new params[:facets]
    @problems = @facets.results.ordered.page params[:page]
    breadcrumb
    add_breadcrumb 'Publicités signalées', problems_path
  end

  def analyzed
    @steps = Problem::Step.analyzed
    @categories = Taxonomy.find_by(slug: 'mauvaises-pratiques')
                          .categories
                          .ordered
    breadcrumb
    add_breadcrumb 'Nos analyses'
  end

  def show
    @problem = Problem.find(params.expect(:id))
    breadcrumb
    add_breadcrumb Problem.model_name.human(count: 2), problems_path
    add_breadcrumb @problem
  end
end

app/views/admin/problems/_form.html.erb
<%= simple_form_for [:admin, @problem] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="row">
    <div class="col-lg-9">
      <%= f.input :title %>
    </div>
    <div class="col-lg-3">
      <%= f.input :year %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-4">
      <%= f.input :image %>
      <%= f.association :organizations, as: :check_boxes %>
      <%= f.association :step, include_blank: false, as: :radio_buttons %>
      <% Taxonomy.all.ordered.each do |taxonomy| %>
        <%= f.association :categories,
                          label: taxonomy,
                          as: :check_boxes,
                          collection: taxonomy.categories.ordered %>
      <% end %>
    </div>
    <div class="col-lg-8">
      <%= f.input :description,
                  input_html: { rows: 30 },
                  hint: t('admin.markdown_hint') %>
    </div>
  </div>

  <%= f.button :submit, t('admin.save'), class: button_classes %>
<% end %>

app/views/admin/problems/_list.html.erb
<table class="table">
  <thead>
    <tr>
      <th><%= Problem.human_attribute_name(:image) %></th>
      <th><%= Problem.human_attribute_name(:title) %></th>
      <th><%= Problem.human_attribute_name(:year) %></th>
      <th><%= Problem.human_attribute_name(:reports) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% problems.each do |problem| %>
      <tr>
        <td><%= image_tag problem.image, class: 'img-fluid', width: 200 if problem.image.attached?  %></td>
        <td><%= link_to problem.title, [:admin, problem] %></td>
        <td><%= problem.year %></td>
        <td><%= problem.reports.count %></td>
        <td class="text-end">
          <%= link_to t('admin.show'), [:admin, problem], class: button_classes %>
          <%= link_to t('admin.edit'), [:edit, :admin, problem], class: button_classes %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/problems/_problem.html.erb
<div id="<%= dom_id problem %>">
  <p>
    <strong>Description:</strong>
    <%= problem.description %>
  </p>

</div>

app/views/admin/problems/edit.html.erb
<% content_for :title, @problem %>
<%= render "form", problem: @problem %>

app/views/admin/problems/index.html.erb
<%
title = Problem.model_name.human(count: 2)
title += " — #{@step}" if @step
%>
<% content_for :title, title %>
<%= render 'admin/problems/list', problems: @problems %>

<% content_for :buttons do %>
  <%= link_to t('admin.create'), new_admin_problem_path, class: button_classes %>
<% end %>

app/views/admin/problems/new.html.erb
<% content_for :title, t('admin.create') %>

<%= render "form", problem: @problem %>

app/views/admin/problems/show.html.erb
<% content_for :title, @problem %>

<% if @problem.organizations.any? %>
  <%= render 'problems/analyzed_by', problem: @problem %>
<% end %>

<div class="row mb-5">
  <div class="col-lg-6">
    <%= image_tag @problem.image, class: 'img-fluid rounded' if @problem.image.attached? %>
  </div>
  <div class="col-lg-6">
    <%= simple_format @problem.description %>
  </div>
</div>

<div class="row">
  <% Taxonomy.all.ordered.each do |taxonomy| %>
    <div class="col-lg-3">
      <div class="card">
        <div class="card-header">
          <h2 class="h4"><%= link_to taxonomy, [:admin, taxonomy] %></h2>
        </div>
        <div class="card-body">
          <% @problem.categories.where(taxonomy: taxonomy).each do |category| %>
            <%= link_to category, [:admin, category] %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="card">
  <div class="card-header">
    <h2 class="h4"><%= Report.model_name.human(count: 2) %></h2>
  </div>
  <div class="card-body">
    <%= render 'admin/reports/list', reports: @problem.reports %>
  </div>
</div>

<% if @problem.organizations.any? %>
  <div class="card">
    <div class="card-header">
      <h2 class="h4"><%= Problem.human_attribute_name(:organizations) %></h2>
    </div>
    <div class="card-body">
      <%= render 'admin/organizations/list', organizations: @problem.organizations %>
    </div>
  </div>
<% end %>

<% content_for :buttons do %>
  <%= link_to t('admin.edit'), edit_admin_problem_path(@problem), class: button_classes %>
<% end %>