config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    namespace :reports do
      resources :steps
    end
    namespace :problems do
      resources :steps
    end
    resources :reports, only: [:index, :show, :edit, :update]
    resources :taxonomies, :categories, :problems, :pages
    resources :organizations
    get 'analytics' => 'analytics#index'
    root to: "dashboard#index"
  end

  resources :reports, only: :create
  get 'publicites' => 'problems#index', as: :problems
  get 'publicites/:id' => 'problems#show', as: :problem
  get 'analyses' => 'problems#analyzed', as: :analyzed_problems
  get 'organisations/:slug' => 'organizations#show', as: :organization
  get ':taxonomy_slug' => 'categories#index', as: :taxonomy, constraints: lambda { |request|
    request.path.remove("/").in? Taxonomy.pluck(:slug)
  }
  get ':taxonomy_slug/:category_slug' => 'categories#show', as: :category

  get 'up' => "rails/health#show", as: :rails_health_check
  
  root to: 'pages#index'
  
  match "*slug" => "pages#show", via: :get, constraints: lambda { |request|
    request.path.exclude? 'rails/active_storage'
  }
end

app/models/report.rb
# == Schema Information
#
# Table name: reports
#
#  id               :uuid             not null, primary key
#  author_email     :string
#  author_pseudonym :string
#  brand            :string
#  description      :text
#  link             :string
#  title            :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  problem_id       :uuid
#  step_id          :uuid
#
# Indexes
#
#  index_reports_on_problem_id  (problem_id)
#  index_reports_on_step_id     (step_id)
#
# Foreign Keys
#
#  fk_rails_...  (problem_id => problems.id)
#  fk_rails_...  (step_id => report_steps.id)
#
class Report < ApplicationRecord
  include WithSteps

  has_and_belongs_to_many :categories
  belongs_to :problem, optional: true

  validates_presence_of :brand, :description, :author_pseudonym, on: :create

  scope :ordered, -> { order(created_at: :desc) }

  has_one_attached :image
  has_many_attached :files

  def to_s
    title.blank? ? "#{id}" : "#{title}"
  end
end

app/models/report/step.rb
# == Schema Information
#
# Table name: report_steps
#
#  id          :uuid             not null, primary key
#  description :text
#  position    :integer          default(0)
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Report::Step < ApplicationRecord

  has_many :reports

  scope :ordered, -> { order(:position) }

  def to_s
    "#{title}"
  end
end

app/controllers/admin/reports/steps_controller.rb
class Admin::Reports::StepsController < Admin::ApplicationController
  before_action :set_report_step, only: %i[ show edit update destroy ]

  def index
    @steps = Report::Step.ordered
  end

  def show
  end

  def new
    @step = Report::Step.new
  end

  def edit
  end

  def create
    @step = Report::Step.new(step_params)
    if @step.save
      redirect_to admin_reports_step_path(@step), notice: t('admin.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @step.update(step_params)
      redirect_to admin_reports_step_path(@step), notice: t('admin.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @step.destroy!
    redirect_to admin_reports_steps_path, status: :see_other, notice: t('admin.deleted')
  end

  private

    def set_report_step
      @step = Report::Step.find(params.expect(:id))
    end

    def step_params
      params.expect(report_step: [ :title, :description, :position ])
    end
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < Admin::ApplicationController
  before_action :set_report, only: %i[ show edit update ]

  def index
    @reports = Report.all.ordered
    if params[:step]
      @step = Report::Step.find(params[:step])
      @reports = @reports.where(step: @step)
    end
  end

  def show
  end

  def edit
  end

  def update
    if @report.update(report_params)
      redirect_to [:admin, @report], notice: t('admin.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  protected

  def set_report
    @report = Report.find(params.expect(:id))
  end

  def report_params
    params.expect(report: [ :problem_id, :step_id ])
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def create
    @report = Report.create(report_params)
    if @report.valid?
      redirect_to root_path, notice: "Merci pour ce signalement !"
    else
      @problems =  Problem.for_home
      render 'pages/index'
    end
  end

  private

  def report_params
    params.expect(report: [ 
      :title, :description, :link, :image, :brand,
      :author_pseudonym, :author_email, files: [],
      category_ids: []
    ])
  end
end

app/views/admin/reports/_list.html.erb
<table class="table">
  <thead>
    <tr>
      <th><%= Report.human_attribute_name(:title) %></th>
      <th><%= Report.human_attribute_name(:brand) %></th>
      <th><%= Report.human_attribute_name(:step) %></th>
      <th><%= Report.human_attribute_name(:problem) %></th>
      <th><%= Report.human_attribute_name(:created_at) %></th>
    </tr>
  </thead>
  <tbody>
    <% reports.each do |report| %>
      <tr>
        <td><%= link_to report, [:admin, report] %></td>
        <td><%= report.brand %></td>
        <td><%= report.step %></td>
        <td><%= report.problem %></td>
        <td><%= l report.created_at.to_date %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/reports/edit.html.erb
<% content_for :title, @report %>

<%= simple_form_for [:admin, @report] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <%= f.association :step,
                    collection: Report::Step.ordered,
                    as: :radio_buttons %>
  <%= f.association :problem %>

  <%= f.button :submit, t('admin.save'), class: button_classes %>
<% end %>

app/views/admin/reports/index.html.erb
<%
title = Report.model_name.human(count: 2)
title += " — #{@step}" if @step
%>
<% content_for :title, title %>
<%= render 'admin/reports/list', reports: @reports %>

app/views/admin/reports/show.html.erb
<% content_for :title, @report %>

<div class="row mb-5">
  <div class="col-lg-6">
    <%= simple_format @report.description %>
    <hr>
    <% if @report.link.present? %>
      <a href="<%= @report.link %>" target="_blank"><%= @report.link %></a>
      <hr>
    <% end %>
    <%= @report.author_pseudonym %><br>
    <%= @report.author_email %><br>
    <div class="my-5">
      <% Taxonomy.for_reports.each do |taxonomy| %>
        <div class="mb-3">
          <p class="form-label">
            <%= taxonomy %>
          </p>
          <%= @report.categories.where(taxonomy: taxonomy).to_sentence %>
        </div>
      <% end %>
    </div>
    <div class="my-5">
      <p class="form-label">
        <%= Report.human_attribute_name(:problem) %>
      </p>
      <% if @report.problem.present? %>
        <%= link_to @report.problem, [:admin, @report.problem] %>
      <% else %>
        Non associé
      <% end %>
    </div>
    <div class="my-5">
      <p class="form-label">
      <%= Report.human_attribute_name(:step) %>
      </p>
      <%
      Report::Step.ordered.each do |step| 
      active = step == @report.step
      classes = active ? 'btn btn-primary' : 'btn btn-light'
      %>
      <%= link_to step, 
                  admin_report_path(@report, report: { step_id: step.id } ), 
                  method: :put, 
                  disabled: !active,
                  class: classes %>
      <% end %>
    </div>
  </div>
  <div class="col-lg-6">
    <% if @report.image.attached? %>
      <div class="mb-5">
        <p>Image</p>
        <%= image_tag @report.image, class: 'img-fluid' if @report.image.attached? %>
      </div>
    <% end %>

    <% if @report.files.any? %>
      <div>
        <p>Fichiers</p>
        <% @report.files.each do |file| %>
          <div class="mb-5">
            <% if file.image? %>
              <div class="mb-2">
                <%= image_tag file, class: 'img-fluid' %>
              </div>
            <% elsif file.video? %>
              <div class="mb-2">
                <%= video_tag file, controls: true %>
              </div>
            <% end %>
            <%= file.filename %>
            — 
            <%= link_to 'Télécharger', rails_blob_url(file, disposition: :attachment) %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<% content_for :buttons do %>
  <%= link_to t('admin.edit'), edit_admin_report_path(@report), class: button_classes %>
<% end %>